<div style="background-color: #ef84d3; padding: 20px; border-radius: 10px">

# Sprint 10 - Analítica de datos en Pandas
</div>

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

# ⭐️ Nivel 1

</div>

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 1 - Importar y ordenar el DataFrame
________________________________________________________________________________________________________________
- Importa como DataFrame el archivo `sprint10.xlsx` con los nombres de columnas correctos.
- Ordena por país de origen y en caso de empate, por nombre de ciudad.
- Muestra las primeras 10 filas.
- Realiza un print comprobando que el DNI sólo tiene valores únicos.
</div>

In [306]:
import pandas as pd
import numpy as np

In [307]:
# - Importa como DataFrame el archivo `sprint10.xlsx`, como había visto q los nombres de campos estaban mal modifiqué con header y también eliminé la columna de indice anterior
df = pd.read_excel('sprint10.xlsx', header=3)
df = df.drop('Unnamed: 0', axis=1)
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
0,Inês,Ferreira Silva,16928694K,Portugal,Lisboa,25,2,1953,D,1.144 €,NaN,1.0,Grup B
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1.253 €,1.0,NaN,Grup A
2,Fatima,Fassi,38141675A,Marroc,Rabat,6,11,2005,A,1.441 €,1.0,NaN,Grup A
3,Khadija,Bennani Bennani,59157262R,Marroc,Rabat,20,1,1995,D,1.944 €,NaN,1.0,Grup B
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1.043 €,NaN,1.0,Grup A
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Marta,Ferrer Ferrer,25161375F,Espanya,Sevilla,1,6,1951,D,1.216 €,NaN,1.0,Grup B
996,Joan,García,52145541P,Espanya,Sevilla,11,4,1959,H,971 €,NaN,1.0,Grup A
997,Laia,Ferrer Martínez,69760120X,Espanya,Barcelona,11,11,1980,D,682 €,NaN,1.0,Grup A
998,Jordi,García,82947791W,Espanya,Barcelona,23,5,1984,H,1.699 €,1.0,NaN,Grup C
999,Clara,Sánchez López,89253307W,Espanya,Bilbao,1,8,1952,D,1.217 €,NaN,1.0,Grup A

In [308]:
df['Fills'].value_counts(dropna=False)

Fills
NaN    594
1.0    406
Name: count, dtype: int64

In [309]:
# Verifico nulos y tipos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nom                1000 non-null   str
 1   Cognoms            1000 non-null   str
 2   DNI                1000 non-null   str
 3   País d'origen      1000 non-null   str
 4   Ciutat             1000 non-null   str
 5   Dia de Naixement   1000 non-null   int64
 6   Mes de Naixement   1000 non-null   int64
 7   Any de Naixement   1000 non-null   int64
 8   Gènere             1000 non-null   str
 9   Salari mensual     1000 non-null   str
 10  Fills              406 non-null    float64
 11  No Fills           594 non-null    float64
 12  Grup Professional  1000 non-null   str
dtypes: float64(2), int64(3), str(8)
memory usage: 155.7 KB

In [310]:
df['Salari mensual'].describe()  # profundizo en uno de los campos a transformar

count        1000
unique        767
top       1.441 €
freq            4
Name: Salari mensual, dtype: object

In [311]:
df[
    'Salari mensual'
] = (  # transformación sencilla quitando símbolos y poniendo en float
    df['Salari mensual']
    .str.replace('€', '', regex=False)
    .str.replace('.', '', regex=False)
    .astype(float)
)

In [312]:
# Ordena por país de origen y en caso de empate, por nombre de ciudad.
df = df.sort_values(by=["País d'origen", 'Ciutat'], ascending=[True, True])
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951.0,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1769.0,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2013.0,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1557.0,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2754.0,1.0,NaN,Grup D
...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2033.0,NaN,1.0,Grup B
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1130.0,1.0,NaN,Grup A
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1023.0,NaN,1.0,Grup A
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1197.0,NaN,1.0,Grup A
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1405.0,1.0,NaN,Grup A

In [313]:
Muetro_10 = df.head(10)
Muetro_10

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951.0,NaN,1.0,Grup A
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1769.0,1.0,NaN,Grup B
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2013.0,NaN,1.0,Grup B
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1557.0,1.0,NaN,Grup B
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2754.0,1.0,NaN,Grup D
871,Lea,Fischer,14773153R,Alemanya,Berlín,9,9,1986,D,1370.0,1.0,NaN,Grup A
281,Lea,Müller,23266650S,Alemanya,Hamburg,14,4,2003,D,1314.0,NaN,1.0,Grup A
435,Anna,Müller,83274277X,Alemanya,Hamburg,1,1,1987,D,2464.0,NaN,1.0,Grup C
444,Laura,Schmidt Müller,60161784X,Alemanya,Hamburg,15,6,1987,NC,2035.0,1.0,NaN,Grup C
487,Lukas,Müller Fischer,60982309S,Alemanya,Hamburg,28,3,1971,H,2042.0,NaN,1.0,Grup B

In [314]:
# Realiza un print comprobando que el DNI sólo tiene valores únicos.
print(df['DNI'].is_unique)

True

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 2 - Transformaciones de columnas
________________________________________________________

- Crea una columna de nombre completo.
- Crea una columna indicando si la persona nació en España.
- Pon el DNI como índice del DataFrame.
- Renombra `Día de Nacimiento`, `Mes de Nacimiento`, `Año de Nacimiento` a `Día`, `Mes`, `Año`.
- Sustituye `H`→`Hombre`, `D`→`Mujer`, `A`→`Otros`, `NC`→NaN.
- Muestra todos los cambios en una sola tabla.

In [315]:
# nueva columna nombre completo q esté compuesta por la concatenación de las columbas nom y cognom:
df['Nombre_completo'] = df['Nom'] +  ' ' + df['Cognoms']
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951.0,NaN,1.0,Grup A,Mia Schneider Fischer
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1557.0,1.0,NaN,Grup B,Mia Fischer
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2754.0,1.0,NaN,Grup D,Jonas Schneider
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2033.0,NaN,1.0,Grup B,Emily Taylor Jones
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1130.0,1.0,NaN,Grup A,George Brown Jones
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1023.0,NaN,1.0,Grup A,Olivia Brown Brown
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1197.0,NaN,1.0,Grup A,Isla Jones Brown
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1405.0,1.0,NaN,Grup A,William Smith

In [316]:
# Español Si o no:
df['Español'] = df["País d'origen"].apply(
    lambda Origen: 'SI' if Origen == 'Espanya' else 'NO'
)
df

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español
21,Mia,Schneider Fischer,28973553Z,Alemanya,Berlín,22,10,1976,A,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO
154,Laura,Schneider Fischer,37399141L,Alemanya,Berlín,2,2,1958,D,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO
224,Lea,Schneider Schneider,37368317L,Alemanya,Berlín,23,10,2005,D,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO
278,Mia,Fischer,21390098Z,Alemanya,Berlín,11,8,1950,D,1557.0,1.0,NaN,Grup B,Mia Fischer,NO
602,Jonas,Schneider,44060014R,Alemanya,Berlín,22,11,1985,H,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
547,Emily,Taylor Jones,89577876S,Regne Unit,Manchester,28,3,1958,D,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO
728,George,Brown Jones,57441590Y,Regne Unit,Manchester,27,12,1979,H,1130.0,1.0,NaN,Grup A,George Brown Jones,NO
751,Olivia,Brown Brown,58204038A,Regne Unit,Manchester,28,8,1952,A,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO
854,Isla,Jones Brown,28367234K,Regne Unit,Manchester,28,3,1999,D,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO
872,William,Smith,82046699J,Regne Unit,Manchester,19,5,1997,H,1405.0,1.0,NaN,Grup A,William Smith,NO

In [317]:
# Compruebo que tambien funciona para español:
Esp = df[df['Español'] == 'SI']
Esp

,Nom,Cognoms,DNI,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español
1,Clara,Sánchez Martínez,27724652S,Espanya,Barcelona,18,3,1996,D,1253.0,1.0,NaN,Grup A,Clara Sánchez Martínez,SI
4,Toni,Sánchez García,69630528M,Espanya,Barcelona,9,8,1999,H,1043.0,NaN,1.0,Grup A,Toni Sánchez García,SI
9,Toni,Martínez,14219925Z,Espanya,Barcelona,16,5,1964,H,891.0,NaN,1.0,Grup A,Toni Martínez,SI
10,Oriol,Sánchez,40695825B,Espanya,Barcelona,27,7,1965,H,1250.0,NaN,1.0,Grup A,Oriol Sánchez,SI
13,Toni,Castells Romero,74222289K,Espanya,Barcelona,13,4,1961,H,1438.0,NaN,1.0,Grup B,Toni Castells Romero,SI
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,Laia,Sánchez,42807414J,Espanya,València,17,7,1967,D,2255.0,NaN,1.0,Grup C,Laia Sánchez,SI
949,Núria,Martínez Ferrer,38147748A,Espanya,València,4,11,1976,D,1028.0,NaN,1.0,Grup A,Núria Martínez Ferrer,SI
958,Oriol,Sánchez García,48749091Z,Espanya,València,16,7,1965,H,1273.0,NaN,1.0,Grup A,Oriol Sánchez García,SI
961,Clara,Romero García,29019539A,Espanya,València,8,2,1989,D,1246.0,1.0,NaN,Grup A,Clara Romero García,SI
991,Carla,Ferrer Martínez,22942395H,Espanya,València,3,5,1992,D,1714.0,NaN,1.0,Grup B,Carla Ferrer Martínez,SI

In [318]:
# Cambio el índice poniendo 'DNI

df.set_index('DNI', inplace=True)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia de Naixement,Mes de Naixement,Any de Naixement,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1557.0,1.0,NaN,Grup B,Mia Fischer,NO
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,H,1130.0,1.0,NaN,Grup A,George Brown Jones,NO
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,A,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,D,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,H,1405.0,1.0,NaN,Grup A,William Smith,NO

In [319]:
# Renombro la columnas 'X de Naixement' como Dia, Mes, Año:

df = df.rename(
    columns={
        'Dia de Naixement': 'Dia',
        'Mes de Naixement': 'Mes',
        'Any de Naixement': 'Año',
    }
)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,A,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,D,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,D,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,D,1557.0,1.0,NaN,Grup B,Mia Fischer,NO
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,H,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,D,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,H,1130.0,1.0,NaN,Grup A,George Brown Jones,NO
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,A,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,D,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,H,1405.0,1.0,NaN,Grup A,William Smith,NO

In [320]:
# Sustituyo `H`→`Hombre`, `D`→`Mujer`, `A`→`Otros`, `NC`→NaN.

df['Gènere'] = df['Gènere'].replace(
    {'H': 'Hombre', 'D': 'Mujer', 'A': 'Otros', 'NC': 'NaN'}
)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 3 - Columna Hijos con .apply()
_________________________________________________________
- Junta las columnas `Hijos` y `No Hijos` en una sola columna usando `.apply()` y una función definida por ti.
- La nueva columna debe llamarse `Hijos` con valores `Sí` o `No`.

In [321]:
# Junto las columnas `Hijos` y `No Hijos` en una sola columna usando `.apply()`

def combina_columnas(fila):
    if pd.notnull(fila['Fills']) and pd.isnull(fila['No Fills']):
        return 'Si'
    elif pd.notnull(fila['No Fills']) and pd.isnull(fila['Fills']):
        return 'No'
    else:
        return 'Dato raro'


df['Hijos'] = df.apply(combina_columnas, axis=1)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español,Hijos
DNI,,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO,No
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO,Si
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO,No
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO,Si
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO,Si
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO,No
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO,Si
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO,No
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO,No
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO,Si

In [322]:
df[df['Hijos'] == 'Dato raro']  # compruebo nva columna

Empty DataFrame
Columns: [Nom, Cognoms, País d'origen, Ciutat, Dia, Mes, Año, Gènere, Salari mensual, Fills, No Fills, Grup Professional, Nombre_completo, Español, Hijos]
Index: []

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 4 - Tabla resumen por Género
_____________________________________________________
- Crea una tabla resumen con el sueldo medio, mediana, mínimo y máximo por Género.
- Ordena la tabla por sueldo medio.

In [323]:
resumen = (
    df.groupby('Gènere')['Salari mensual']
    .agg(['mean', 'median', 'min', 'max'])
    .sort_values('mean')
    .round(2)
)
print('Resúmen de salario por género:')
resumen

Resúmen de salario por género:

           mean  median    min     max
Gènere
Mujer   1469.44  1361.5  665.0  3021.0
NaN     1568.87  1443.0  758.0  2969.0
Otros   1626.59  1545.0  703.0  3175.0
Hombre  1643.25  1531.0  737.0  3356.0

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 5 - Tabla pivot sueldo por Género y País
_________________________________________________________
- Crea una tabla pivot: salario medio por género (filas) y país de origen (columnas).<br>
- Añade las medias a los márgenes.<br>
**(EXTRA):** <br> 
- Aplica formato condicional para resaltar valores más elevados.

In [324]:
tabla_pivot = pd.pivot_table(
    df,
    index= 'Gènere',
    columns= "País d'origen",
    values=  'Salari mensual',
    aggfunc= 'mean',
    margins=True,
    margins_name= 'Total'
).round(2)
print('Salario medio por género y país:')
tabla_pivot

Salario medio por género y país:

País d'origen,Alemanya,Argentina,Colòmbia,Espanya,França,Itàlia,Marroc,Mèxic,Portugal,Regne Unit,Total
Gènere,,,,,,,,,,,
Hombre,2067.43,1583.29,1554.67,1682.11,1389.25,1672.88,1531.00,1625.00,1497.00,1162.56,1643.25
Mujer,1804.31,1291.80,1497.75,1460.16,1566.47,1247.18,1405.21,1517.80,1488.55,1489.46,1469.44
NaN,1931.50,1135.67,1252.00,1597.14,1573.00,1316.00,1365.50,1583.00,1553.50,1758.00,1568.87
Otros,951.00,1141.00,1030.00,1706.18,NaN,1423.00,1365.00,1372.00,1765.00,1921.00,1626.59
Total,1858.35,1431.68,1489.13,1582.16,1465.36,1421.17,1441.69,1559.08,1527.23,1448.33,1561.46

In [325]:
# - Aplico formato condicional para resaltar valores (Extra)

Estilo = (
    tabla_pivot
    .style
    .format('{:.2f}')
    .highlight_max(axis=1)                          # Fosforito en los valores máximos    
)
print('Salario medio por género y país:  (Resaltando los valores mas elevados)')
Estilo

Salario medio por género y país:  (Resaltando los valores mas elevados)

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 6 - Columna de Edad
_______________________
- Crea una columna `Fecha_Nacimiento` en formato Datetime combinando `Día`, `Mes` y `Año`.
- Define una función que, dada una fecha de nacimiento, calcule la edad actual.
- Aplica la función para crear una nueva columna `Edad` en el DataFrame.

In [326]:
import pandas as pd
from datetime import datetime

df['Fecha_Nacimiento'] = pd.to_datetime(
    df['Año'].astype(str)
    + '-'
    + df['Mes'].astype(str)
    + '-'
    + df['Dia'].astype(str),
    format='%Y-%m-%d',
    errors='coerce',
)
df

,Nom,Cognoms,País d'origen,Ciutat,Dia,Mes,Año,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español,Hijos,Fecha_Nacimiento
DNI,,,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,22,10,1976,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO,No,1976-10-22
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,2,2,1958,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO,Si,1958-02-02
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,23,10,2005,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO,No,2005-10-23
21390098Z,Mia,Fischer,Alemanya,Berlín,11,8,1950,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO,Si,1950-08-11
44060014R,Jonas,Schneider,Alemanya,Berlín,22,11,1985,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO,Si,1985-11-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,28,3,1958,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO,No,1958-03-28
57441590Y,George,Brown Jones,Regne Unit,Manchester,27,12,1979,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO,Si,1979-12-27
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,28,8,1952,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO,No,1952-08-28
28367234K,Isla,Jones Brown,Regne Unit,Manchester,28,3,1999,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO,No,1999-03-28
82046699J,William,Smith,Regne Unit,Manchester,19,5,1997,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO,Si,1997-05-19

In [327]:
hoy = datetime.now()
def calcula_edad(fecha_nac):
    edad_dias = (hoy - fecha_nac).days
    return edad_dias // 365

In [328]:
df['Edad'] = df['Fecha_Nacimiento'].apply(calcula_edad)
df = df.drop(columns=['Dia', 'Mes', 'Año'])
df

,Nom,Cognoms,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español,Hijos,Fecha_Nacimiento,Edad
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO,No,1976-10-22,49
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO,Si,1958-02-02,68
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO,No,2005-10-23,20
21390098Z,Mia,Fischer,Alemanya,Berlín,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO,Si,1950-08-11,75
44060014R,Jonas,Schneider,Alemanya,Berlín,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO,Si,1985-11-22,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO,No,1958-03-28,68
57441590Y,George,Brown Jones,Regne Unit,Manchester,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO,Si,1979-12-27,46
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO,No,1952-08-28,73
28367234K,Isla,Jones Brown,Regne Unit,Manchester,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO,No,1999-03-28,27
82046699J,William,Smith,Regne Unit,Manchester,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO,Si,1997-05-19,28

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

# ⭐️⭐️ Nivel 2

</div>

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 1 - Incremento salarial
________________________________
- Adjunta la columna `Incremento` al DataFrame usando el siguiente DataFrame de referencia:

```python
df_increment = pd.DataFrame({"Grupo": ["Grupo A'", "Grupo B", "Grupo C", "Grupo D"],
                             "Incremento": ["5%", "3,5%", "2%", "8%"]})
```

- Actualiza la columna salario según los porcentajes indicados.
- No modifiques los incrementos manualmente; usa código Python para las conversiones.

In [329]:
# df recibido en el ejercicio:

df_increment = pd.DataFrame(
    {
        "Grupo": ["Grupo A", "Grupo B", "Grupo C", "Grupo D"],
        "Incremento": ["5%", "3,5%", "2%", "8%"],
    }
)

In [330]:
df_increment['Incremento'].dtypes

In [331]:
# traducción de datos
df_increment['Grupo'] = df_increment['Grupo'].str.replace('Grupo', 'Grup')  

df_increment.rename(                    # Modif nombres campos
    columns={
        'Grupo': 'Grup Professional',
        'Incremento': 'Increment',
    },                                 
    inplace=True,
)

df_increment['Increment'] = (            # Conversión de String a Float para poder hacer cálculo
    df_increment['Increment']
    .str.replace('%', '', regex=False)
    .str.replace(',','.', regex=False)
    .astype(float)
)


df_increment

  Grup Professional  Increment
0            Grup A        5.0
1            Grup B        3.5
2            Grup C        2.0
3            Grup D        8.0

In [337]:
df

,Nom,Cognoms,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español,Hijos,Fecha_Nacimiento,Edad
DNI,,,,,,,,,,,,,,
28973553Z,Mia,Schneider Fischer,Alemanya,Berlín,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO,No,1976-10-22,49
37399141L,Laura,Schneider Fischer,Alemanya,Berlín,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO,Si,1958-02-02,68
37368317L,Lea,Schneider Schneider,Alemanya,Berlín,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO,No,2005-10-23,20
21390098Z,Mia,Fischer,Alemanya,Berlín,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO,Si,1950-08-11,75
44060014R,Jonas,Schneider,Alemanya,Berlín,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO,Si,1985-11-22,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,Emily,Taylor Jones,Regne Unit,Manchester,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO,No,1958-03-28,68
57441590Y,George,Brown Jones,Regne Unit,Manchester,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO,Si,1979-12-27,46
58204038A,Olivia,Brown Brown,Regne Unit,Manchester,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO,No,1952-08-28,73
28367234K,Isla,Jones Brown,Regne Unit,Manchester,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO,No,1999-03-28,27
82046699J,William,Smith,Regne Unit,Manchester,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO,Si,1997-05-19,28

In [ ]:
'''Aqui realizo el merge entre dos dataframes, 
el original con el que venía trabajando y el que terminé de formatear '''

df = df.reset_index() # No quiero perder a DNI (lo transformo en columna) 
ndf = pd.merge(df, df_increment, on='Grup Professional') # Uso como referencia el campo 'Grup Professional'para traer los datos del incremento a calcular
ndf = ndf.set_index('DNI') #una vez hecho el merge, vuelvo a poner la columna como indice
ndf

,index,Nom,Cognoms,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español,Hijos,Fecha_Nacimiento,Edad,Increment
DNI,,,,,,,,,,,,,,,,
28973553Z,0,Mia,Schneider Fischer,Alemanya,Berlín,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO,No,1976-10-22,49,5.0
37399141L,1,Laura,Schneider Fischer,Alemanya,Berlín,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO,Si,1958-02-02,68,3.5
37368317L,2,Lea,Schneider Schneider,Alemanya,Berlín,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO,No,2005-10-23,20,3.5
21390098Z,3,Mia,Fischer,Alemanya,Berlín,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO,Si,1950-08-11,75,3.5
44060014R,4,Jonas,Schneider,Alemanya,Berlín,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO,Si,1985-11-22,40,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,995,Emily,Taylor Jones,Regne Unit,Manchester,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO,No,1958-03-28,68,3.5
57441590Y,996,George,Brown Jones,Regne Unit,Manchester,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO,Si,1979-12-27,46,5.0
58204038A,997,Olivia,Brown Brown,Regne Unit,Manchester,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO,No,1952-08-28,73,5.0
28367234K,998,Isla,Jones Brown,Regne Unit,Manchester,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO,No,1999-03-28,27,5.0
82046699J,999,William,Smith,Regne Unit,Manchester,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO,Si,1997-05-19,28,5.0

In [343]:
# Calculo del nuevo Salario
ndf['N_Salari'] = ndf['Salari mensual'] * (1 + ndf['Increment'] / 100).round(2)
ndf

,index,Nom,Cognoms,País d'origen,Ciutat,Gènere,Salari mensual,Fills,No Fills,Grup Professional,Nombre_completo,Español,Hijos,Fecha_Nacimiento,Edad,Increment,N_Salari
DNI,,,,,,,,,,,,,,,,,
28973553Z,0,Mia,Schneider Fischer,Alemanya,Berlín,Otros,951.0,NaN,1.0,Grup A,Mia Schneider Fischer,NO,No,1976-10-22,49,5.0,998.55
37399141L,1,Laura,Schneider Fischer,Alemanya,Berlín,Mujer,1769.0,1.0,NaN,Grup B,Laura Schneider Fischer,NO,Si,1958-02-02,68,3.5,1822.07
37368317L,2,Lea,Schneider Schneider,Alemanya,Berlín,Mujer,2013.0,NaN,1.0,Grup B,Lea Schneider Schneider,NO,No,2005-10-23,20,3.5,2073.39
21390098Z,3,Mia,Fischer,Alemanya,Berlín,Mujer,1557.0,1.0,NaN,Grup B,Mia Fischer,NO,Si,1950-08-11,75,3.5,1603.71
44060014R,4,Jonas,Schneider,Alemanya,Berlín,Hombre,2754.0,1.0,NaN,Grup D,Jonas Schneider,NO,Si,1985-11-22,40,8.0,2974.32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89577876S,995,Emily,Taylor Jones,Regne Unit,Manchester,Mujer,2033.0,NaN,1.0,Grup B,Emily Taylor Jones,NO,No,1958-03-28,68,3.5,2093.99
57441590Y,996,George,Brown Jones,Regne Unit,Manchester,Hombre,1130.0,1.0,NaN,Grup A,George Brown Jones,NO,Si,1979-12-27,46,5.0,1186.50
58204038A,997,Olivia,Brown Brown,Regne Unit,Manchester,Otros,1023.0,NaN,1.0,Grup A,Olivia Brown Brown,NO,No,1952-08-28,73,5.0,1074.15
28367234K,998,Isla,Jones Brown,Regne Unit,Manchester,Mujer,1197.0,NaN,1.0,Grup A,Isla Jones Brown,NO,No,1999-03-28,27,5.0,1256.85
82046699J,999,William,Smith,Regne Unit,Manchester,Hombre,1405.0,1.0,NaN,Grup A,William Smith,NO,Si,1997-05-19,28,5.0,1475.25

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 2 - Exportar por Grupo Profesional
__________________________
Utilizando un bucle, exporta en 4 archivos (`.xlsx` o `.csv`) los datos de cada Grupo Profesional.
Ejemplo: `datos_GrupoA.xlsx`, `datos_GrupoB.xlsx`, ...

Exporta además un 5º DataFrame con:
- Número de trabajadores por Grupo Profesional
- Sueldo medio
- Edad media

In [344]:
# Utilizando un bucle, exporta en 4 archivos (`.xlsx` o `.csv`) los datos de cada Grupo Profesional.
# Ejemplo: `datos_GrupoA.xlsx`, `datos_GrupoB.xlsx`,
def exporta_grupos(df):
    for grupo, datos_grupo in df.groupby('Grup Professional'):
        nombre_archivo = f'datos_{grupo}.xlsx'
        datos_grupo.to_excel(nombre_archivo, index=False)

In [345]:
exporta_grupos(df)

In [346]:
df_5 = df.groupby('Grup Professional').agg(
    num_empleados = ('DNI', 'count'),
    edad_media    = ('Edad', 'mean'),
    salari_mitja  = ('Salari mensual', 'mean')
).round(2)
df_5

                   num_empleados  edad_media  salari_mitja
Grup Professional
Grup A                       490       49.26       1155.55
Grup B                       318       48.00       1666.23
Grup C                       137       51.06       2244.31
Grup D                        55       45.15       2871.13

In [347]:
df_5.to_csv('datos_5.csv', index='Grup Professional')

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

# ⭐️⭐️⭐️ Nivel 3

</div>

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 1 - Función de visualización automática
____________________________
Crea una función que tome un DataFrame y genere (y exporte) un gráfico para cada columna:

- **Histograma/Boxplot** si la variable es numérica
- **Barras de valores más frecuentes** si es categórica
- **Barras de años más frecuentes** si está en formato fecha

La función debe funcionar con **cualquier** DataFrame.

Muestra el resultado con un dataset de ejemplo de `seaborn` (ej: `iris`, `penguins` o `titanic`).

In [348]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [349]:

df = sns.load_dataset('titanic')
df.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [350]:
from pandas.api.types import (
    is_bool_dtype,
    is_numeric_dtype,
    is_datetime64_any_dtype
)

def auto_plots(df):
    for col in df.columns:
        serie = df[col].dropna()
        if is_bool_dtype(serie):                            # 1º bolean porque los 1 y o pueden confundirse con números y queremos aplicar gráficos de barras
            plt.figure()
            serie.value_counts().plot(kind='bar')
            plt.title(f'Valores más frecuentes de {col}')
            plt.savefig(f'{col}_bar.png')

        elif is_numeric_dtype(serie):                       # 2º si es numérico
            plt.figure()
            sns.histplot(serie, kde=False)
            plt.title(f'Histograma de {col}')
            plt.savefig(f'{col}_hist.png')

        elif is_datetime64_any_dtype(serie):                # 3º si es fecha
            plt.figure()
            serie.dt.year.value_counts().sort_index().plot(kind='bar')
            plt.title(f'Años más frecuentes en {col}')
            plt.savefig(f'{col}_years.png')

        else:
            plt.figure()                                    # 4º si no es numérico o bool
            serie.value_counts().head(10).plot(kind='bar')
            plt.title(f'Valores más frecuentes de {col}')
            plt.savefig(f'{col}_bar.png')

        plt.close()

In [352]:
# Ejercicio 1 - Auto plots
auto_plots(df)

## Ejemplos de salidas:
![Bool](alone_bar.png) ![Str>Categtegorical](alive_bar.png)![Num>Hist](fare_hist.png)

In [357]:
ndf.dtypes

index                         int64
Nom                             str
Cognoms                         str
País d'origen                   str
Ciutat                          str
Gènere                          str
Salari mensual              float64
Fills                       float64
No Fills                    float64
Grup Professional               str
Nombre_completo                 str
Español                         str
Hijos                           str
Fecha_Nacimiento     datetime64[us]
Edad                          int64
Increment                   float64
N_Salari                    float64
dtype: object

In [358]:
# Ejecuto el codigo para comprobar las salidas del ejercicio ejecutado en el Sprint10 (ndf)
auto_plots(ndf)

# Ejemplos de las salidas de ndf:
![Num > hist](N_Salari_hist.png) ![Fechas> años](Fecha_Nacimiento_years.png) ![Categ](Español_bar.png)

In [359]:
iris = sns.load_dataset("iris")
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [361]:
auto_plots(iris)

# Ejemplo Salida Iris:
![alt text](species_bar.png)![alt text](petal_width_hist.png)

In [364]:
peng = sns.load_dataset('penguins')
peng.dtypes

species                  str
island                   str
bill_length_mm       float64
bill_depth_mm        float64
flipper_length_mm    float64
body_mass_g          float64
sex                      str
dtype: object

In [365]:
auto_plots(peng)

# Ejemplo salida Penguins:
![alt text](species_bar.png)![alt text](island_bar.png)![alt text](flipper_length_mm_hist.png)

<div style="background-color: #f4b2e2; padding: 10px; border-radius: 5px;">

### Ejercicio 2 - Ruta mínima entre ciudades de España
______________________________
Carga el archivo `matriu_distancies.xlsx` con los nombres de ciudades como índice y columnas. <br>
-  Elimina `Las Palmas de Gran Canaria` y `Palma`.

Crea una función que, dada la matriz de distancias y una ciudad de origen, proponga la ruta más corta posible (p.ej. yendo siempre a la ciudad más cercana no visitada), devolviendo:
- Lista con el orden de visita
- Distancia total recorrida

**(EXTRA):** ¿Desde qué ciudad la ruta sería más corta con este algoritmo?

In [366]:
import pandas as pd

df_dist = pd.read_excel('matriu_distancies.xlsx',
    index_col=0       # ciudades como índice
)
df_dist

,Barcelona,Valencia,Sevilla,Zaragoza,Málaga,Murcia,Palma,Las Palmas de Gran Canaria,Bilbao,Alicante,Córdoba,Valladolid,Vigo,Gijón,Hospitalet de Llobregat
Barcelona,NaN,303.0,831.0,256.0,770.0,471.0,206.0,2175.0,469.0,407.0,711.0,576.0,908.0,686.0,7.0
Valencia,303.0,NaN,541.0,246.0,468.0,177.0,260.0,1874.0,473.0,125.0,421.0,441.0,766.0,632.0,297.0
Sevilla,831.0,541.0,NaN,646.0,158.0,433.0,791.0,1355.0,703.0,495.0,121.0,486.0,588.0,685.0,824.0
Zaragoza,256.0,246.0,646.0,NaN,628.0,408.0,377.0,2001.0,246.0,368.0,535.0,320.0,652.0,444.0,250.0
Málaga,770.0,468.0,158.0,628.0,NaN,323.0,695.0,1406.0,739.0,391.0,133.0,549.0,716.0,766.0,763.0
Murcia,471.0,177.0,433.0,408.0,323.0,NaN,372.0,1723.0,606.0,69.0,320.0,510.0,800.0,726.0,465.0
Palma,206.0,260.0,791.0,377.0,695.0,372.0,NaN,2093.0,621.0,303.0,671.0,664.0,1000.0,820.0,204.0
Las Palmas de Gran Canaria,2175.0,1874.0,1355.0,2001.0,1406.0,1723.0,2093.0,NaN,2022.0,1792.0,1470.0,1790.0,1682.0,1925.0,2168.0
Bilbao,469.0,473.0,703.0,246.0,739.0,606.0,621.0,2022.0,NaN,583.0,618.0,232.0,486.0,223.0,465.0
Alicante,407.0,125.0,495.0,368.0,391.0,69.0,303.0,1792.0,583.0,NaN,379.0,515.0,821.0,722.0,401.0
Córdoba,711.0,421.0,121.0,535.0,133.0,320.0,671.0,1470.0,618.0,379.0,NaN,419.0,589.0,634.0,704.0
Valladolid,576.0,441.0,486.0,320.0,549.0,510.0,664.0,1790.0,232.0,515.0,419.0,NaN,337.0,224.0,570.0
Vigo,908.0,766.0,588.0,652.0,716.0,800.0,1000.0,1682.0,486.0,821.0,589.0,337.0,NaN,289.0,902.0
Gijón,686.0,632.0,685.0,444.0,766.0,726.0,820.0,1925.0,223.0,722.0,634.0,224.0,289.0,NaN,681.0
Hospitalet de Llobregat,7.0,297.0,824.0,250.0,763.0,465.0,204.0,2168.0,465.0,401.0,704.0,570.0,902.0,681.0,NaN

In [367]:
# Eliminar las dos ciudades que no cuentan
df_dist = df_dist.drop(index=['Las Palmas de Gran Canaria', 'Palma'],
                       columns=['Las Palmas de Gran Canaria', 'Palma'])
df_dist

,Barcelona,Valencia,Sevilla,Zaragoza,Málaga,Murcia,Bilbao,Alicante,Córdoba,Valladolid,Vigo,Gijón,Hospitalet de Llobregat
Barcelona,NaN,303.0,831.0,256.0,770.0,471.0,469.0,407.0,711.0,576.0,908.0,686.0,7.0
Valencia,303.0,NaN,541.0,246.0,468.0,177.0,473.0,125.0,421.0,441.0,766.0,632.0,297.0
Sevilla,831.0,541.0,NaN,646.0,158.0,433.0,703.0,495.0,121.0,486.0,588.0,685.0,824.0
Zaragoza,256.0,246.0,646.0,NaN,628.0,408.0,246.0,368.0,535.0,320.0,652.0,444.0,250.0
Málaga,770.0,468.0,158.0,628.0,NaN,323.0,739.0,391.0,133.0,549.0,716.0,766.0,763.0
Murcia,471.0,177.0,433.0,408.0,323.0,NaN,606.0,69.0,320.0,510.0,800.0,726.0,465.0
Bilbao,469.0,473.0,703.0,246.0,739.0,606.0,NaN,583.0,618.0,232.0,486.0,223.0,465.0
Alicante,407.0,125.0,495.0,368.0,391.0,69.0,583.0,NaN,379.0,515.0,821.0,722.0,401.0
Córdoba,711.0,421.0,121.0,535.0,133.0,320.0,618.0,379.0,NaN,419.0,589.0,634.0,704.0
Valladolid,576.0,441.0,486.0,320.0,549.0,510.0,232.0,515.0,419.0,NaN,337.0,224.0,570.0
Vigo,908.0,766.0,588.0,652.0,716.0,800.0,486.0,821.0,589.0,337.0,NaN,289.0,902.0
Gijón,686.0,632.0,685.0,444.0,766.0,726.0,223.0,722.0,634.0,224.0,289.0,NaN,681.0
Hospitalet de Llobregat,7.0,297.0,824.0,250.0,763.0,465.0,465.0,401.0,704.0,570.0,902.0,681.0,NaN